# Generated by Django 5.1.2 on 2025-03-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app_img', '0002_rol_alter_item_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
